name: test-coverage

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system deps
        run: sudo apt-get update

      # install deps INSIDE the package dir
      - name: Install R deps
        working-directory: OpenStats
        run: |
          Rscript -e 'install.packages(c("remotes", "covr", "ggplot2", "tinytest"))'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Run coverage
        working-directory: OpenStats
        run: |
          Rscript -e 'covr::codecov(path = ".", type = c("tests"))'
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
