name: Publish blog (Quarto) to GitHub Pages

on:
  push:
    branches: [ "main" ]
    paths:
      - 'blog/**'
      - '.github/workflows/publish-blog.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pandoc (required by Quarto)
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R (for knitr)
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("knitr", "rmarkdown"))'

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # - name: Render blog/
      #   uses: quarto-dev/quarto-actions/render@v2
      #   with:
      #     path: blog
      - name: Render full site
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: blog

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
